### ISSUE TITLE
Liquibase generateChangelog, liquibase diff, liquibase diffChangeLog, liquibase snapshot are not working for Snowflake Database

### ISSUE THREAD

**Issue by shilpagupta-axtria** [liquibase/liquibase-snowflake#61] opened 2021-03-06 12:49 UTC
Liquibase generateChangelog, liquibase diff, liquibase diffChangeLog, liquibase snapshot are not working for Snowflake Database

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1333) by [Unito](https://www.unito.io)

**Comment by niravparikh** [comment] 2021-12-23 17:19
liquibase --includeObjects="view:LEDGER_VW" diff-changelog            
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 11:18:17 (version 4.6.2 #886 built at 2021-11-30 16:20+0000)
Liquibase Version: 4.6.2
Liquibase Community 4.6.2 by Liquibase

Unexpected error running Liquibase: java.lang.NullPointerException


We generate the change log for snowflake tables, but it does not work for generating the change log for views, stored procedures..

**Comment by FBurguer** [comment] 2022-06-27 17:17
It seems this is not reproducible on liquibase 4.12, maybe this can be fixed on your environment when you upgrade to our latest version. If you get the same error again, this can have something to do with your liquibase configuration, I recommend reading step by step how to do a properties file for Snowflake. 
This is how my properties file looks like:

```
username=*username here*
password=*password here*
changeLogFile=*changelog file name here*
url= jdbc:snowflake://<userID>.<region>.aws.snowflakecomputing.com/?db=<dbName>&schema=<shemaName>
```
Check if you are missing something.
If any of the things above didnt fixed your issue, please feel free to make a new issue on the Liquibase Community board. Thanks!

Test Environment:
OS: Windows 10
Java 8

**Closed** 2022-07-01 21:07 UTC
